### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by Megachip** [jsamaniegog/dnsinventory#1]
use it?

**Comment by jsamaniegog** [comment]
Hi @Megachip ,

this plugin is not finished (neither versioned), however it is functional, if you want to use it it's installed like any other GLPI plugin, see: http://wiki.glpi-project.org/doku.php?id=en:plugins
then you must add a server in configuration menu and configure the automatic action named dnsinventory. For more information about GLPI go to: http://glpi-project.org/

Regards.

**Comment by Megachip** [comment]
@jsamaniegog I've installed it already and added an DNS Server. But except some php exceptions there where no other actions to do... Add dns records, scan for dns records etc :/
